// ⚠️ AUTO-GENERATED BY RYSING BRIDGE. DO NOT EDIT.
// Source: iOS App Enums (Found recursively via @ExportToTS)

export const SceneTypes = [
  "Dialogue",
  "Narration",
  "InternalMonologue",
] as const;

export const SceneIntroOutro = [
  "intro",
  "outro",
  "event",
] as const;

export const ActionTypes = [
  "textInput",
  "dialogChoice",
  "checkboxButtonChoices",
  "radioButtonChoices",
  "habitTracker",
  "timedCommitment",
  "dateSelection",
  "ratingScale",
  "structuredLog",
  "progressTracker",
  "checkIn",
] as const;

export const NPCAssetID = [
  "char_1",
  "HoodedFigure",
  "mentor_elf_green",
  "demon_inertia",
  "demon_doubt",
] as const;

export const RewardTypes = [
  "CharacterXP_Action_Habit",
  "CharacterXP_Action_Cognitive",
  "CharacterXP_Action_Standard",
  "CharacterXP_FloorClear_Small",
  "CharacterXP_FloorClear_Medium",
  "CharacterXP_FloorClear_High",
  "CharacterXP_DungeonClear_Small",
  "CharacterXP_DungeonClear_Medium",
  "CharacterXP_DungeonClear_High",
  "CharacterXP_Quest_Base",
  "AttributeXP_Contextual",
  "AttributeXP_Specific",
  "AttributeXP_Specific_Medium",
  "AttributeXP_Specific_High",
  "AttributeXP_ClassPrimary_Medium",
  "AttributeXP_Quest_Base",
  "Title_Reward",
  "Item_Reward",
  "Hint_Reward",
] as const;

export const QuestFocuses = [
  "body",
  "mind",
  "spirit",
  "routine",
  "social",
] as const;

export const EffortTiers = [
  "trivial",
  "low",
  "moderate",
  "significant",
  "heroic",
] as const;

